server output restored

diff --git a/.github/workflows/ci_e2e_cypress.yml b/.github/workflows/ci_e2e_cypress.yml
--- a/.github/workflows/ci_e2e_cypress.yml
+++ b/.github/workflows/ci_e2e_cypress.yml
@@ -214,5 +214,10 @@ jobs:
           name: video-${{ matrix.name }}
           path: cypress/videos/
       - name: Print server output
-        run: cat output.txt
+        run: |
+          echo "📁 Startup logs:"
+          cat .github/logs/start-uwazi-logs.txt || echo "Startup log file not found"
+          echo
+          echo "📁 Health-check logs:"
+          cat .github/logs/health-check-logs.txt || echo "Health-check log file not found"
         if: failure()
diff --git a/.github/workflows/ci_e2e_puppeteer.yml b/.github/workflows/ci_e2e_puppeteer.yml
--- a/.github/workflows/ci_e2e_puppeteer.yml
+++ b/.github/workflows/ci_e2e_puppeteer.yml
@@ -117,5 +117,10 @@ jobs:
           ELASTICSEARCH_URL: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
           TRANSPILED: true
       - name: Print server output
-        run: cat output.txt
+        run: |
+          echo "📁 Startup logs:"
+          cat .github/logs/start-uwazi-logs.txt || echo "Startup log file not found"
+          echo
+          echo "📁 Health-check logs:"
+          cat .github/logs/health-check-logs.txt || echo "Health-check log file not found"
         if: failure()
